name: Deploy to Debian Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ secrets.TARGET_FOLDER }}
