name: Deploy to Debian Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
#      - name: Checkout code
      - uses: actions/checkout@v3
      - run: cd ${{ secrets.TARGET_FOLDER }}
      - run: git fetch
      - run: git pull
