name: Deploy to Debian Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: web-deploy-test 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ secrets.TARGET_FOLDER }}
